repos:
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.16.0"
    hooks:
      - id: terraform-docs-go
        args: ["markdown", "table", "--recursive", "--recursive-path", "gcp", "--output-file", "README.md", "./composition"]
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.16.0"
    hooks:
      - id: terraform-docs-go
        args: ["markdown", "table", "--recursive", "--recursive-path", "gcp", "--output-file", "README.md", "./infrastructure"]
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.16.0"
    hooks:
      - id: terraform-docs-go
        args: ["markdown", "table", "--recursive", "--recursive-path", "gcp", "--output-file", "README.md", "./resource"]